SELECT count(USER.USER_ID), USER.USER_ID, USER.NAME FROM 
(SELECT USER_ID, CREATED_AT FROM 
twitter.POST where POST.CREATED_AT>= '2020-03-01 00:00:00' AND POST.CREATED_AT< '2020-03-02 00:00:00') as FIRSTMARCH
inner join twitter.USER on FIRSTMARCH.USER_ID=USER.USER_ID
group by USER.USER_ID; 